In [ ]:
import numpy as np

Q1

In [ ]:
n=np.array([1,2,3,6,4,5])

In [ ]:
r=n[::-1]

In [ ]:
print(r)

[5 4 6 3 2 1]


Q2

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])

In [ ]:
equal=np.array_equal(arr1,arr2)

In [ ]:
print(equal)

True


In [ ]:
elementwise=arr1 == arr2

In [ ]:
print(elementwise)

[[ True  True]
 [ True  True]]


Q3

In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])

In [ ]:
def findind(arr):
  vals,counts=np.unique(arr,return_counts=True)
  countmax=counts.max()
  modes=vals[counts==countmax]
  for  mode in modes:
    indices=np.where(arr==mode)[0]
    return indices

In [ ]:
findind(x)

array([0, 5, 7, 8, 9])

In [ ]:
y=np.array([1,1,1,2,3,4,2,4,3,3])

In [ ]:
findind(y)

array([0, 1, 2])

Q4

In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')

In [ ]:
total=gfg.sum()

In [ ]:
totalrow=gfg.sum(axis=1)

In [ ]:
totalcolumn=gfg.sum(axis=0)

In [ ]:
print(total)
print('')
print(totalrow)
print('')
print(totalcolumn)

45

[[14]
 [16]
 [15]]

[[20  9 16]]
